version: '3.8'

services:
  web:
    build: .
    image: mywebapp
    ports:
      - "127.0.0.1:15000:5000"
    depends_on:
      - db
    networks:
      - frontend
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    read_only: true
    security_opt:
      - no-new-privileges:true
    mem_limit: 256m
    pids_limit: 100
    env_file:
      - .env

  db:
    image: postgres:13
    networks:
      - backend
    env_file:
      - .env
    read_only: true
    security_opt:
      - no-new-privileges:true
    mem_limit: 512m
    pids_limit: 100

networks:
  frontend:
  backend: